config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  # defaults format: :json do
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'login', to: 'sessions#new'

  post 'sign_up', to: 'login_users#create'
  get 'sign_up', to: 'login_users#new'
  resources :login_user_confirmations, only: %i[create new edit], param: :confirmation_token

  post '/subscriber_user', to: 'subscriber_user#create', as: :subscriber_user

  post '/question/:id/yes', to: 'home#answer_yes', as: 'answer_yes'
  post '/question/:id/no', to: 'home#answer_no', as: 'answer_no'
  get '/reset_form', to: 'home#reset_form'

  get '/start_checking', to: 'home#start_checking'
  # end
end

app/models/login_user.rb
# frozen_string_literal: true

class LoginUser < ApplicationRecord
  has_secure_password

  MAILER_FROM_EMAIL = 'no-reply@tano.com'
  CONFIRMATION_TOKEN_EXPIRATION = 10.minutes

  before_save :downcase_email

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, presence: true, uniqueness: true
  validates :state, inclusion: { in: CitizenshipChecker::FINAL_STATES }, if: :should_validate?

  def confirm!
    update_columns(confirmed_at: Time.current)
  end

  def confirmed?
    confirmed_at.present?
  end

  def generate_confirmation_token
    signed_id expires_in: CONFIRMATION_TOKEN_EXPIRATION, purpose: :confirm_email
  end

  def unconfirmed?
    !confirmed?
  end

  def send_confirmation_email!
    confirmation_token = generate_confirmation_token
    LoginUserMailer.confirmation(self, confirmation_token).deliver_now
  end

  private

  def downcase_email
    self.email = email.downcase
  end

  def should_validate?
    state.present?
  end
end

app/controllers/login_users_controller.rb
# frozen_string_literal: true

# frozen_string_literal: true

class LoginUsersController < ApplicationController
  before_action :redirect_if_authenticated, only: %i[create new]

  def create
    @login_user = LoginUser.new(login_user_params)
    if @login_user.save
      @login_user.send_confirmation_email!

      redirect_to root_path, info: 'Por favor, siga las instrucciones enviadas por email para confirmar su cuenta.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @login_user = LoginUser.new
  end

  private

  def login_user_params
    params.require(:login_user).permit(:email, :password, :password_confirmation, :state)
  end
end

app/helpers/login_users_helper.rb
# frozen_string_literal: true

module LoginUsersHelper
end

app/views/login_users/new.html.erb
<div class="hero-body">
  <div class="container has-text-centered">
    <div class="column is-4 is-offset-4">
      <h3 class="title has-text-black">Login</h3>

      <hr class="login-hr"></hr>

      <div class="box">
        <%= form_with model: @login_user, url: sign_up_path do |form| %>
          <%= render partial: "shared/form_errors", locals: { object: form.object } %>
        <div class="field">
          <div class="control">
            <%= form.label :email %>
            <%= form.email_field :email,required: true, class:"input is-large" %>
          </div>
        </div>

        <div class="field">
          <div class="control">
            <%= form.label :password %>
            <%= form.password_field :password, required:true, class:"input is-large" %>
          </div>
        </div>

        <div class="field">
          <div class="control">
            <%= form.label :password_confirmation %>
            <%= form.password_field :password_confirmation, required: true, class:"input is-large" %>
          </div>
        </div>
        <%= form.hidden_field :state, value: request.query_parameters['state'] %>
        <%= form.submit "Crear cuenta", class:"button is-block is-success is-large is-fullwidth" %>
        <% end %>
        <p class="has-text-grey">
          <span> Ya tienes una cuenta? <%= link_to 'Iniciar Sesion', login_url %></span>
        </p>
      </div>
    </div>
  </div>
</div>