config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  # defaults format: :json do
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'login', to: 'sessions#new'

  post 'sign_up', to: 'login_users#create'
  get 'sign_up', to: 'login_users#new'
  resources :login_user_confirmations, only: %i[create new edit], param: :confirmation_token

  post '/subscriber_user', to: 'subscriber_user#create', as: :subscriber_user

  post '/question/:id/yes', to: 'home#answer_yes', as: 'answer_yes'
  post '/question/:id/no', to: 'home#answer_no', as: 'answer_no'
  get '/reset_form', to: 'home#reset_form'

  get '/start_checking', to: 'home#start_checking'
  # end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end

  def start_checking
    @checker = if params.key?(:id)
                 CitizenshipChecker.find(params[:id])
               else
                 CitizenshipChecker.create!
               end
  end

  def answer_no
    @checker = CitizenshipChecker.find(params[:id])

    @checker.no! unless CitizenshipChecker::FINAL_STATES.include?(@checker.question.to_sym)
    redirect_to start_checking_path(id: @checker.id)
  end

  def answer_yes
    @checker = CitizenshipChecker.find(params[:id])
    @checker.yes! unless CitizenshipChecker::FINAL_STATES.include?(@checker.question.to_sym)
    redirect_to start_checking_path(id: @checker.id)
  end

  def reset_form
    CitizenshipChecker.delete_all
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/home/index.html.erb
<div class="columns is-centered mt-4">
  <div class="column is-half">
    <div class="card has-text-centered">
      <div class="card-content">
        <div class="content">
          <h1>
            HOLA!
          </h1>

          <h3>
            Vamos a realizarte unas preguntas para saber que proceso podes realizar
          </h3>

          <%= button_to 'Comenzar', start_checking_url, class:"button is-block is-success is-large is-fullwidth", method: :get %>
        </div>
        <%
=begin%>
 <% if user_signed_in? %>
        <div class="content">
          <%= button_to 'Cerrar Sesion', logout_url, method: :delete %>
        </div>
        <% else %>
        <div class="content">
          <span>Inicia sesion si ya respondiste nuestro cuestionario</span>
          <%= link_to 'Iniciar Sesion', login_url %>
        </div>
        <% end %> 
<%
=end%>
      </div>
    </div>
  </div>
</div>

app/views/home/start_checking.html.erb
<%= button_to 'Cerrar Sesion', logout_url, method: :delete if user_signed_in? %>

<div class="columns is-centered mt-6">
  <div class="column is-half">
    <div class="card has-text-centered">
      <div class="card-content">
        <div class="content">
          <h3> <%= t("citizenship_checker.questions.#{@checker.question}") %></h3>

          <div class= "columns <%= @checker.final_state? ? 'is-hidden' : '' %>">
            <div class="column">
              <%= button_to 'Si!', "/question/#{@checker.id}/yes", class: "button is-success", method: :post %>
            </div>
            <div class="column">
              <%= button_to 'No!', "/question/#{@checker.id}/no", class: "button is-danger", method: :post %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <% if @checker.final_state?%>
    <div class="card has-text-centered">
      <div class="card-content">
        <div class="content">
          Dejanos tu email si queres recibir mas informacion sobre como continuar con tu proceso!
          <div class="field">
            <div class="control">
            <%= form_with model: SubscriberUser.new, url: subscriber_user_path do |form| %>
              <%= form.label :email %>
              <%= form.email_field :email,required: true, class:"input is-large" %>
              <%= form.hidden_field :citizenship_checker_id, value: request.query_parameters['id'] %>
              <hr class="login-hr"></hr>
              <%= form.submit "Enviarme informacion", class:"button is-block is-success is-large is-fullwidth" %>
            <% end %>
            </div>

        </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%
=begin%>
Registrate para que podamos seguir ayudandote! <%= link_to "Crear cuenta", sign_up_url(state: @checker.question)%>
 <%= button_to 'Reset!', "/reset_form", method: :get %> 
<%
=end%>